---
# show the complex interactions of variables
# from various sources
# play variables
# vars file
# host vars files
# group vars files


# show a variable installed in a play
- name: Play variables
  hosts: variables-rocky
  gather_facts: false
  vars:
    app: cat
  tasks:
    - name: Not dog
      debug:
        var: app


# show a variable from a vars file in the play
- name: Play varsfiles
  hosts: variables-amazon
  gather_facts: false
  vars_files:
    - vars/system-amazon.yml

  tasks:
    - name: Not relay
      debug:
        var: app

# show a variable from a vars file included
# as a task
- name: Play include_vars
  hosts: variables-ubuntu
  gather_facts: false
  tasks:
    - name: Load local variables
      include_vars: vars/system-ubuntu.yml

    - name: Not excel
      debug:
        var: app

# show a variable on the first vars file
# found based on the hosts facts
- name: First come
  hosts: variables
  gather_facts: true
  tasks:
    - name: Find closest match
      include_vars: "{{ item }}"
      with_first_found:
        - vars/os-{{ ansible_distribution }}.yml
        - vars/family-{{ ansible_os_family }}.yml
        - vars/default.yml
    - name: Show closest match
      debug:
        var: meal

# show a variable from a host_vars file based
# on the inventory host
- name: Host vars
  hosts: variables
  gather_facts: false
  tasks:
    - name: Where
      debug:
        var: location

# show a variable from a group vars file
# based on the inventory group
- name: Group vars
  hosts: variables
  gather_facts: false
  tasks:
    - name: Where
      debug:
        var: location

    - name: Drink my friends, drink!
      debug:
        var: blood
